name: dev

on:
  pull_request: 
    branches: [ main ] 
    paths-ignore:
      - '**.md'
    
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  Jira_linkage:
    name: Jira_linkage
    runs-on: ubuntu

    steps:

    - name: Establish Jira linkage
      run: echo Establishment_TODO....
  